# Generated by Django 4.2.20 on 2025-04-13 17:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'plan_payment',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='enter details', max_length=500, null=True)),
                ('Duration', models.TextField(choices=[('ONE MONTH', 'ONE MONTH'), ('SIX MONTH', 'SIX MONTH'), ('TWELVE MONTH', 'TWELVE MONTH'), ('CUSTOM', 'CUSTOM')], default='')),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(default='', max_length=500)),
                ('profile_image', models.ImageField(blank=True, default='images/demo.jpg', null=True, upload_to='profiles')),
                ('phoneno', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None, unique=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proof')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('current_plan', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
        ),
    ]
